default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: developmentguru

test:
  <<: *default
  database: testguru

production:
  <<: *default
  database: productionguru
